# Generated by Django 4.2.16 on 2024-11-22 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_userprofile_delete_customuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="NoDueSlip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_name", models.CharField(max_length=100)),
                ("roll_no", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                (
                    "hostel",
                    models.CharField(
                        default="Hostel Name Not Provided", max_length=100
                    ),
                ),
                (
                    "room_no",
                    models.CharField(default="Room Number Not Provided", max_length=10),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NOCRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_name", models.CharField(max_length=100)),
                ("roll_no", models.CharField(max_length=15)),
                ("request_description", models.TextField()),
                ("google_drive_link", models.URLField()),
                (
                    "email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.userprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LORRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_name", models.CharField(max_length=100)),
                ("roll_no", models.CharField(max_length=15)),
                ("request_description", models.TextField()),
                ("google_drive_link", models.URLField()),
                (
                    "email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.userprofile",
                    ),
                ),
            ],
        ),
    ]
