# Generated by Django 4.2.16 on 2024-11-22 18:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_nodueslip_nocrequest_lorrequest"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="NoDueSlip",
            new_name="NoDueSlip2",
        ),
    ]
