# Generated by Django 4.2.16 on 2024-11-22 19:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_rename_nodueslip_nodueslip2"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="NoDueSlip2",
            new_name="NoDueSlip",
        ),
    ]
