# Generated by Django 4.2.16 on 2024-11-22 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_rename_nodueslip2_nodueslip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nodueslip",
            name="roll_no",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="nodueslip",
            name="room_no",
            field=models.CharField(default="Room Number Not Provided", max_length=100),
        ),
    ]
